[{"_path":"/til/junit-swtbot","_draft":false,"_partial":false,"_locale":"en","_empty":false,"title":"Testes com SWTBot","description":"Testes com SWTBot","excerpt":{"type":"root","children":[{"type":"element","tag":"code","props":{"code":"SWTBotMenu windowMenu = bot.menu(\"Window\");\nwindowMenu.click();\n\nSWTBotMenu showViewMenu = windowMenu.menu(\"ShowView\");\nshowViewMenu.click();\n\nSWTBotMenu otherMenu = showViewMenu.menu(\"Other...\");\notherMenu.click();\n\nSWTBotTree tree = bot.tree(0);\nSWTBotTreeItem tItem = tree.getTreeItem(\"General\").expand();\ntItem.getNode(\"Console\").doubleClick();\n","language":"java"},"children":[{"type":"element","tag":"pre","props":{},"children":[{"type":"element","tag":"code","props":{"__ignoreMap":""},"children":[{"type":"text","value":"SWTBotMenu windowMenu = bot.menu(\"Window\");\nwindowMenu.click();\n\nSWTBotMenu showViewMenu = windowMenu.menu(\"ShowView\");\nshowViewMenu.click();\n\nSWTBotMenu otherMenu = showViewMenu.menu(\"Other...\");\notherMenu.click();\n\nSWTBotTree tree = bot.tree(0);\nSWTBotTreeItem tItem = tree.getTreeItem(\"General\").expand();\ntItem.getNode(\"Console\").doubleClick();\n"}]}]}]},{"type":"element","tag":"h2","props":{"id":"referências"},"children":[{"type":"text","value":"Referências"}]},{"type":"element","tag":"ul","props":{},"children":[{"type":"element","tag":"li","props":{},"children":[{"type":"element","tag":"a","props":{"href":"http://eclipseo.blogspot.com/2010/12/simple-test-using-swtbot.html","rel":["nofollow"]},"children":[{"type":"text","value":"A Simple Test using SWTBOT !!"}]}]}]}]},"date":"2019-11-12T00:00:00.000Z","draft":true,"tags":["swtbot","java","junit"],"Thumbnail":"img/headers/junit.webp","body":{"type":"root","children":[{"type":"element","tag":"code","props":{"code":"SWTBotMenu windowMenu = bot.menu(\"Window\");\nwindowMenu.click();\n\nSWTBotMenu showViewMenu = windowMenu.menu(\"ShowView\");\nshowViewMenu.click();\n\nSWTBotMenu otherMenu = showViewMenu.menu(\"Other...\");\notherMenu.click();\n\nSWTBotTree tree = bot.tree(0);\nSWTBotTreeItem tItem = tree.getTreeItem(\"General\").expand();\ntItem.getNode(\"Console\").doubleClick();\n","language":"java"},"children":[{"type":"element","tag":"pre","props":{},"children":[{"type":"element","tag":"code","props":{"__ignoreMap":""},"children":[{"type":"element","tag":"span","props":{"class":"line"},"children":[{"type":"element","tag":"span","props":{},"children":[{"type":"text","value":"SWTBotMenu windowMenu = bot.menu(\"Window\");\nwindowMenu.click();\n\nSWTBotMenu showViewMenu = windowMenu.menu(\"ShowView\");\nshowViewMenu.click();\n\nSWTBotMenu otherMenu = showViewMenu.menu(\"Other...\");\notherMenu.click();\n\nSWTBotTree tree = bot.tree(0);\nSWTBotTreeItem tItem = tree.getTreeItem(\"General\").expand();\ntItem.getNode(\"Console\").doubleClick();"}]}]}]}]}]},{"type":"element","tag":"h2","props":{"id":"referências"},"children":[{"type":"text","value":"Referências"}]},{"type":"element","tag":"ul","props":{},"children":[{"type":"element","tag":"li","props":{},"children":[{"type":"element","tag":"a","props":{"href":"http://eclipseo.blogspot.com/2010/12/simple-test-using-swtbot.html","rel":["nofollow"]},"children":[{"type":"text","value":"A Simple Test using SWTBOT !!"}]}]}]}],"toc":{"title":"","searchDepth":2,"depth":2,"links":[{"id":"referências","depth":2,"text":"Referências"}]}},"_type":"markdown","_id":"content:til:junit-swtbot.md","_source":"content","_file":"til/junit-swtbot.md","_extension":"md"},{"_path":"/til/junit-rules","_draft":false,"_partial":false,"_locale":"en","_empty":false,"title":"JUnit Rules","description":"JUnit Rules","excerpt":{"type":"root","children":[{"type":"element","tag":"p","props":{},"children":[{"type":"element","tag":"a","props":{"href":"https://www.infoq.com/news/2009/07/junit-4.7-rules","rel":["nofollow"]},"children":[{"type":"text","value":"https://www.infoq.com/news/2009/07/junit-4.7-rules"}]}]},{"type":"element","tag":"p","props":{},"children":[{"type":"text","value":"Unit 4.7, which has just reached Release Candidate stage, includes a significant new feature: Rules."}]},{"type":"element","tag":"p","props":{},"children":[{"type":"text","value":"Rules are, in essence, another extension mechanism for JUnit, which can be used to add functionality to JUnit on a per-test basis. Most examples of custom runners in earlier versions of JUnit can be replaced by Rules. As described in an earlier blog post about the feature:"}]},{"type":"element","tag":"p","props":{},"children":[{"type":"text","value":"In JUnit 3 you could also manipulate the test running process itself in various ways. One of the prices of the simplicity of JUnit 4 was the loss of this “meta-testing”. It doesn’t affect simple tests, but for more powerful tests it can be constraining. The object framework style of JUnit 3 lent itself to extension by default. The DSL style of JUnit 4 doesn’t. Last night we brought back meta-testing, but much cleaner and simpler than before.\nIn addition to the capability of adding rules, a number of core rules have been added:"}]},{"type":"element","tag":"p","props":{},"children":[{"type":"text","value":"TemporaryFolder: Allows test to create files and folders that are guaranteed to be deleted after the test is run. This is a common need for tests that work with the filesystem and want to run in isolation.\nExternalResource: A pattern for resources that need to be set up in advance and are guaranteed to be torn down after the test runs. This will be useful for tests that work with sockets, embedded servers, and the like.\nErrorCollector: Allows the test to continue running after a failure and report all errors at the end of the test. Useful when a test verifies a number of independent conditions (although that may itself be a 'test smell').\nExpectedException: Allows a test to specify expected exception types and messages in the test itself.\nTimeout: Applies the same timeout to all tests in a class.\nIf you'd like to see an example of a rule in action, here's a test using the TemporaryFolder and ExpectedException rules:"}]},{"type":"element","tag":"p","props":{},"children":[{"type":"text","value":"public class DigitalAssetManagerTest {"}]},{"type":"element","tag":"code","props":{"code":"@Rule\npublic TemporaryFolder tempFolder = new TemporaryFolder();\n\n@Rule\npublic ExpectedException exception = ExpectedException.none();\n\n@Test\npublic void countsAssets() throws IOException {\n    File icon = tempFolder.newFile(\"icon.webp\");\n    File assets = tempFolder.newFolder(\"assets\");\n    createAssets(assets, 3);\n\n    DigitalAssetManager dam = new DigitalAssetManager(icon, assets);\n    assertEquals(3, dam.getAssetCount());\n}\n\nprivate void createAssets(File assets, int numberOfAssets) throws IOException {\n    for (int index = 0; index < numberOfAssets; index++) {\n        File asset = new File(assets, String.format(\"asset-%d.mpg\", index));\n        Assert.assertTrue(\"Asset couldn't be created.\", asset.createNewFile());\n    }\n}\n\n@Test\npublic void throwsIllegalArgumentExceptionIfIconIsNull() {\n    exception.expect(IllegalArgumentException.class);\n    exception.expectMessage(\"Icon is null, not a file, or doesn't exist.\");\n    new DigitalAssetManager(null, null);\n}\n"},"children":[{"type":"element","tag":"pre","props":{},"children":[{"type":"element","tag":"code","props":{"__ignoreMap":""},"children":[{"type":"text","value":"@Rule\npublic TemporaryFolder tempFolder = new TemporaryFolder();\n\n@Rule\npublic ExpectedException exception = ExpectedException.none();\n\n@Test\npublic void countsAssets() throws IOException {\n    File icon = tempFolder.newFile(\"icon.webp\");\n    File assets = tempFolder.newFolder(\"assets\");\n    createAssets(assets, 3);\n\n    DigitalAssetManager dam = new DigitalAssetManager(icon, assets);\n    assertEquals(3, dam.getAssetCount());\n}\n\nprivate void createAssets(File assets, int numberOfAssets) throws IOException {\n    for (int index = 0; index < numberOfAssets; index++) {\n        File asset = new File(assets, String.format(\"asset-%d.mpg\", index));\n        Assert.assertTrue(\"Asset couldn't be created.\", asset.createNewFile());\n    }\n}\n\n@Test\npublic void throwsIllegalArgumentExceptionIfIconIsNull() {\n    exception.expect(IllegalArgumentException.class);\n    exception.expectMessage(\"Icon is null, not a file, or doesn't exist.\");\n    new DigitalAssetManager(null, null);\n}\n"}]}]}]},{"type":"element","tag":"p","props":{},"children":[{"type":"text","value":"}\nTo make rule development easier, a few base classes for rules have been added:"}]},{"type":"element","tag":"p","props":{},"children":[{"type":"text","value":"Verifier: A base class for rules like ErrorCollector that can turn failing tests into passing ones if a verification check is failed.\nTestWatchman: A base class for rules that observe the running of tests without modifying the results.\nRules were called Interceptors when they made their first appearance in earlier builds of JUnit 4.7. In addition to the rules, JUnit 4.7 also includes:"}]},{"type":"element","tag":"p","props":{},"children":[{"type":"text","value":"Some changes to the matchers.\nTests that timeout now show the stack trace; this can help to diagnose the cause of the test timing out.\nImprovements to Javadoc and a few bugs fixed.\nMore information on these features is available in the JUnit 4.7 release notes.  Hamcrest 1.2 support was listed in earlier release notes, but has been rolled back for this release."}]},{"type":"element","tag":"p","props":{},"children":[{"type":"text","value":"While you're waiting for the final release, you can download the release candidate from github, browse org.junit.rules gear, fill out the survey, read about the deadpooling of Kent Beck's JUnit Max, and wait for user reactions to JUnit 4.7 on blogs, friendfeed and twitter."}]}]},"date":"2019-11-12T00:00:00.000Z","draft":true,"tags":["junit"],"Thumbnail":"img/headers/junit.webp","body":{"type":"root","children":[{"type":"element","tag":"p","props":{},"children":[{"type":"element","tag":"a","props":{"href":"https://www.infoq.com/news/2009/07/junit-4.7-rules","rel":["nofollow"]},"children":[{"type":"text","value":"https://www.infoq.com/news/2009/07/junit-4.7-rules"}]}]},{"type":"element","tag":"p","props":{},"children":[{"type":"text","value":"Unit 4.7, which has just reached Release Candidate stage, includes a significant new feature: Rules."}]},{"type":"element","tag":"p","props":{},"children":[{"type":"text","value":"Rules are, in essence, another extension mechanism for JUnit, which can be used to add functionality to JUnit on a per-test basis. Most examples of custom runners in earlier versions of JUnit can be replaced by Rules. As described in an earlier blog post about the feature:"}]},{"type":"element","tag":"p","props":{},"children":[{"type":"text","value":"In JUnit 3 you could also manipulate the test running process itself in various ways. One of the prices of the simplicity of JUnit 4 was the loss of this “meta-testing”. It doesn’t affect simple tests, but for more powerful tests it can be constraining. The object framework style of JUnit 3 lent itself to extension by default. The DSL style of JUnit 4 doesn’t. Last night we brought back meta-testing, but much cleaner and simpler than before.\nIn addition to the capability of adding rules, a number of core rules have been added:"}]},{"type":"element","tag":"p","props":{},"children":[{"type":"text","value":"TemporaryFolder: Allows test to create files and folders that are guaranteed to be deleted after the test is run. This is a common need for tests that work with the filesystem and want to run in isolation.\nExternalResource: A pattern for resources that need to be set up in advance and are guaranteed to be torn down after the test runs. This will be useful for tests that work with sockets, embedded servers, and the like.\nErrorCollector: Allows the test to continue running after a failure and report all errors at the end of the test. Useful when a test verifies a number of independent conditions (although that may itself be a 'test smell').\nExpectedException: Allows a test to specify expected exception types and messages in the test itself.\nTimeout: Applies the same timeout to all tests in a class.\nIf you'd like to see an example of a rule in action, here's a test using the TemporaryFolder and ExpectedException rules:"}]},{"type":"element","tag":"p","props":{},"children":[{"type":"text","value":"public class DigitalAssetManagerTest {"}]},{"type":"element","tag":"code","props":{"code":"@Rule\npublic TemporaryFolder tempFolder = new TemporaryFolder();\n\n@Rule\npublic ExpectedException exception = ExpectedException.none();\n\n@Test\npublic void countsAssets() throws IOException {\n    File icon = tempFolder.newFile(\"icon.webp\");\n    File assets = tempFolder.newFolder(\"assets\");\n    createAssets(assets, 3);\n\n    DigitalAssetManager dam = new DigitalAssetManager(icon, assets);\n    assertEquals(3, dam.getAssetCount());\n}\n\nprivate void createAssets(File assets, int numberOfAssets) throws IOException {\n    for (int index = 0; index < numberOfAssets; index++) {\n        File asset = new File(assets, String.format(\"asset-%d.mpg\", index));\n        Assert.assertTrue(\"Asset couldn't be created.\", asset.createNewFile());\n    }\n}\n\n@Test\npublic void throwsIllegalArgumentExceptionIfIconIsNull() {\n    exception.expect(IllegalArgumentException.class);\n    exception.expectMessage(\"Icon is null, not a file, or doesn't exist.\");\n    new DigitalAssetManager(null, null);\n}\n"},"children":[{"type":"element","tag":"pre","props":{},"children":[{"type":"element","tag":"code","props":{"__ignoreMap":""},"children":[{"type":"element","tag":"span","props":{"class":"line"},"children":[{"type":"element","tag":"span","props":{},"children":[{"type":"text","value":"@Rule\npublic TemporaryFolder tempFolder = new TemporaryFolder();\n\n@Rule\npublic ExpectedException exception = ExpectedException.none();\n\n@Test\npublic void countsAssets() throws IOException {\n    File icon = tempFolder.newFile(\"icon.webp\");\n    File assets = tempFolder.newFolder(\"assets\");\n    createAssets(assets, 3);\n\n    DigitalAssetManager dam = new DigitalAssetManager(icon, assets);\n    assertEquals(3, dam.getAssetCount());\n}\n\nprivate void createAssets(File assets, int numberOfAssets) throws IOException {\n    for (int index = 0; index < numberOfAssets; index++) {\n        File asset = new File(assets, String.format(\"asset-%d.mpg\", index));\n        Assert.assertTrue(\"Asset couldn't be created.\", asset.createNewFile());\n    }\n}\n\n@Test\npublic void throwsIllegalArgumentExceptionIfIconIsNull() {\n    exception.expect(IllegalArgumentException.class);\n    exception.expectMessage(\"Icon is null, not a file, or doesn't exist.\");\n    new DigitalAssetManager(null, null);\n}"}]}]}]}]}]},{"type":"element","tag":"p","props":{},"children":[{"type":"text","value":"}\nTo make rule development easier, a few base classes for rules have been added:"}]},{"type":"element","tag":"p","props":{},"children":[{"type":"text","value":"Verifier: A base class for rules like ErrorCollector that can turn failing tests into passing ones if a verification check is failed.\nTestWatchman: A base class for rules that observe the running of tests without modifying the results.\nRules were called Interceptors when they made their first appearance in earlier builds of JUnit 4.7. In addition to the rules, JUnit 4.7 also includes:"}]},{"type":"element","tag":"p","props":{},"children":[{"type":"text","value":"Some changes to the matchers.\nTests that timeout now show the stack trace; this can help to diagnose the cause of the test timing out.\nImprovements to Javadoc and a few bugs fixed.\nMore information on these features is available in the JUnit 4.7 release notes.  Hamcrest 1.2 support was listed in earlier release notes, but has been rolled back for this release."}]},{"type":"element","tag":"p","props":{},"children":[{"type":"text","value":"While you're waiting for the final release, you can download the release candidate from github, browse org.junit.rules gear, fill out the survey, read about the deadpooling of Kent Beck's JUnit Max, and wait for user reactions to JUnit 4.7 on blogs, friendfeed and twitter."}]}],"toc":{"title":"","searchDepth":2,"depth":2,"links":[]}},"_type":"markdown","_id":"content:til:junit-rules.md","_source":"content","_file":"til/junit-rules.md","_extension":"md"},{"_path":"/til/junit-excecao","_draft":false,"_partial":false,"_locale":"en","_empty":false,"title":"Testando exceções com junit","description":"Como testar exceções usando o junit.","excerpt":{"type":"root","children":[{"type":"element","tag":"p","props":{},"children":[{"type":"text","value":"Este artigo apresenta uma visão suscinta sobre testes de exceção com JUnit usando o idioma "},{"type":"element","tag":"code-inline","props":{},"children":[{"type":"text","value":"try/fail/catch"}]},{"type":"text","value":", o parâmetro "},{"type":"element","tag":"code-inline","props":{},"children":[{"type":"text","value":"expected"}]},{"type":"text","value":" da anotação "},{"type":"element","tag":"code-inline","props":{},"children":[{"type":"text","value":"@Test"}]},{"type":"text","value":" e a anotação "},{"type":"element","tag":"code-inline","props":{},"children":[{"type":"text","value":"@Rule"}]},{"type":"text","value":".\nCada um dos métodos apresenta prós e contras."}]},{"type":"element","tag":"h2","props":{"id":"usando-bloco-trycatch"},"children":[{"type":"text","value":"Usando bloco try/catch"}]},{"type":"element","tag":"code","props":{"code":"@Test\npublic void example1() {\n    try {\n        find(\"função que deveria lançar uma exceção\");\n        fail();\n        // Ponto que nunca deveria ser alcançado quando o teste passar\n    } catch (NotFoundException e) {\n        assertThat(e.getMessage(), containsString(\"algo que indique que a exceção certa ocorreu\"));\n    }\n    // ... Outras exceções podem ser tratadas aqui.\n}\n","language":"java"},"children":[{"type":"element","tag":"pre","props":{},"children":[{"type":"element","tag":"code","props":{"__ignoreMap":""},"children":[{"type":"text","value":"@Test\npublic void example1() {\n    try {\n        find(\"função que deveria lançar uma exceção\");\n        fail();\n        // Ponto que nunca deveria ser alcançado quando o teste passar\n    } catch (NotFoundException e) {\n        assertThat(e.getMessage(), containsString(\"algo que indique que a exceção certa ocorreu\"));\n    }\n    // ... Outras exceções podem ser tratadas aqui.\n}\n"}]}]}]},{"type":"element","tag":"ul","props":{},"children":[{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Vantagens:"},{"type":"element","tag":"ul","props":{},"children":[{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Ter acesso à exceção para realizar outros procedimentos"}]},{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Poder realizar outros "},{"type":"element","tag":"em","props":{},"children":[{"type":"text","value":"asserts"}]},{"type":"text","value":" na mesma função"}]},{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Funciona bem de os testes forem criado antes"}]}]}]},{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Desvantagens:"},{"type":"element","tag":"ul","props":{},"children":[{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Um erro comum é esquecer de incluir "},{"type":"element","tag":"code-inline","props":{},"children":[{"type":"text","value":"fail()"}]},{"type":"text","value":" como barreira causando um falso positivo"}]}]}]}]},{"type":"element","tag":"h2","props":{"id":"test-expected--exceptionclass"},"children":[{"type":"text","value":"@Test (expected = Exception.class)"}]},{"type":"element","tag":"code","props":{"code":"public void example2() throws NotFoundException {\n    find(\"função que deveria lançar uma exceção\");\n    // Ponto que nunca deveria ser alcançado quando o teste passar\n}\n","language":"java"},"children":[{"type":"element","tag":"pre","props":{},"children":[{"type":"element","tag":"code","props":{"__ignoreMap":""},"children":[{"type":"text","value":"public void example2() throws NotFoundException {\n    find(\"função que deveria lançar uma exceção\");\n    // Ponto que nunca deveria ser alcançado quando o teste passar\n}\n"}]}]}]},{"type":"element","tag":"ul","props":{},"children":[{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Vantagens:"},{"type":"element","tag":"ul","props":{},"children":[{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Sintaxe muito mais concisa"}]},{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Favorece a escrita de teste focados em um único ponto"}]}]}]},{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Desvantagens:"},{"type":"element","tag":"ul","props":{},"children":[{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Não é possível realizar outros testes após o "},{"type":"element","tag":"code-inline","props":{},"children":[{"type":"text","value":"find"}]}]}]}]}]},{"type":"element","tag":"h2","props":{"id":"expectedexception-rule"},"children":[{"type":"text","value":"ExpectedException Rule"}]},{"type":"element","tag":"code","props":{"code":"\n@Test\npublic void example3() throws NotFoundException {\n    exception.expect(NotFoundException.class);\n    exception.expectMessage(containsString(\"algo que indique que a exceção certa ocorreu\"));\n    find(\"função que deveria lançar uma exceção\");\n    // Ponto que nunca deveria ser alcançado quando o teste passar\n}\n","language":"java"},"children":[{"type":"element","tag":"pre","props":{},"children":[{"type":"element","tag":"code","props":{"__ignoreMap":""},"children":[{"type":"text","value":"\n@Test\npublic void example3() throws NotFoundException {\n    exception.expect(NotFoundException.class);\n    exception.expectMessage(containsString(\"algo que indique que a exceção certa ocorreu\"));\n    find(\"função que deveria lançar uma exceção\");\n    // Ponto que nunca deveria ser alcançado quando o teste passar\n}\n"}]}]}]},{"type":"element","tag":"ul","props":{},"children":[{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Vantagens:"},{"type":"element","tag":"ul","props":{},"children":[{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Mais de uma expetativa sobre a mesma exceção podem ser testadas após o teste"}]}]}]},{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Desvantagens:"},{"type":"element","tag":"ul","props":{},"children":[{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Não é possível realizar outros testes após o "},{"type":"element","tag":"code-inline","props":{},"children":[{"type":"text","value":"find"}]}]}]}]}]},{"type":"element","tag":"h2","props":{"id":"referências"},"children":[{"type":"text","value":"Referências"}]},{"type":"element","tag":"ul","props":{},"children":[{"type":"element","tag":"li","props":{},"children":[{"type":"element","tag":"a","props":{"href":"http://baddotrobot.com/blog/2012/03/27/expecting-exception-with-junit-rule/","rel":["nofollow"]},"children":[{"type":"text","value":"Expecting Exceptions JUnit Rule"}]}]}]}]},"date":"2019-11-12T00:00:00.000Z","draft":false,"tags":["java","junit","exceção","try-catch"],"Thumbnail":"img/headers/junit.webp","body":{"type":"root","children":[{"type":"element","tag":"p","props":{},"children":[{"type":"text","value":"Este artigo apresenta uma visão suscinta sobre testes de exceção com JUnit usando o idioma "},{"type":"element","tag":"code-inline","props":{},"children":[{"type":"text","value":"try/fail/catch"}]},{"type":"text","value":", o parâmetro "},{"type":"element","tag":"code-inline","props":{},"children":[{"type":"text","value":"expected"}]},{"type":"text","value":" da anotação "},{"type":"element","tag":"code-inline","props":{},"children":[{"type":"text","value":"@Test"}]},{"type":"text","value":" e a anotação "},{"type":"element","tag":"code-inline","props":{},"children":[{"type":"text","value":"@Rule"}]},{"type":"text","value":".\nCada um dos métodos apresenta prós e contras."}]},{"type":"element","tag":"h2","props":{"id":"usando-bloco-trycatch"},"children":[{"type":"text","value":"Usando bloco try/catch"}]},{"type":"element","tag":"code","props":{"code":"@Test\npublic void example1() {\n    try {\n        find(\"função que deveria lançar uma exceção\");\n        fail();\n        // Ponto que nunca deveria ser alcançado quando o teste passar\n    } catch (NotFoundException e) {\n        assertThat(e.getMessage(), containsString(\"algo que indique que a exceção certa ocorreu\"));\n    }\n    // ... Outras exceções podem ser tratadas aqui.\n}\n","language":"java"},"children":[{"type":"element","tag":"pre","props":{},"children":[{"type":"element","tag":"code","props":{"__ignoreMap":""},"children":[{"type":"element","tag":"span","props":{"class":"line"},"children":[{"type":"element","tag":"span","props":{},"children":[{"type":"text","value":"@Test\npublic void example1() {\n    try {\n        find(\"função que deveria lançar uma exceção\");\n        fail();\n        // Ponto que nunca deveria ser alcançado quando o teste passar\n    } catch (NotFoundException e) {\n        assertThat(e.getMessage(), containsString(\"algo que indique que a exceção certa ocorreu\"));\n    }\n    // ... Outras exceções podem ser tratadas aqui.\n}"}]}]}]}]}]},{"type":"element","tag":"ul","props":{},"children":[{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Vantagens:"},{"type":"element","tag":"ul","props":{},"children":[{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Ter acesso à exceção para realizar outros procedimentos"}]},{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Poder realizar outros "},{"type":"element","tag":"em","props":{},"children":[{"type":"text","value":"asserts"}]},{"type":"text","value":" na mesma função"}]},{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Funciona bem de os testes forem criado antes"}]}]}]},{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Desvantagens:"},{"type":"element","tag":"ul","props":{},"children":[{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Um erro comum é esquecer de incluir "},{"type":"element","tag":"code-inline","props":{},"children":[{"type":"text","value":"fail()"}]},{"type":"text","value":" como barreira causando um falso positivo"}]}]}]}]},{"type":"element","tag":"h2","props":{"id":"test-expected--exceptionclass"},"children":[{"type":"text","value":"@Test (expected = Exception.class)"}]},{"type":"element","tag":"code","props":{"code":"public void example2() throws NotFoundException {\n    find(\"função que deveria lançar uma exceção\");\n    // Ponto que nunca deveria ser alcançado quando o teste passar\n}\n","language":"java"},"children":[{"type":"element","tag":"pre","props":{},"children":[{"type":"element","tag":"code","props":{"__ignoreMap":""},"children":[{"type":"element","tag":"span","props":{"class":"line"},"children":[{"type":"element","tag":"span","props":{},"children":[{"type":"text","value":"public void example2() throws NotFoundException {\n    find(\"função que deveria lançar uma exceção\");\n    // Ponto que nunca deveria ser alcançado quando o teste passar\n}"}]}]}]}]}]},{"type":"element","tag":"ul","props":{},"children":[{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Vantagens:"},{"type":"element","tag":"ul","props":{},"children":[{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Sintaxe muito mais concisa"}]},{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Favorece a escrita de teste focados em um único ponto"}]}]}]},{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Desvantagens:"},{"type":"element","tag":"ul","props":{},"children":[{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Não é possível realizar outros testes após o "},{"type":"element","tag":"code-inline","props":{},"children":[{"type":"text","value":"find"}]}]}]}]}]},{"type":"element","tag":"h2","props":{"id":"expectedexception-rule"},"children":[{"type":"text","value":"ExpectedException Rule"}]},{"type":"element","tag":"code","props":{"code":"\n@Test\npublic void example3() throws NotFoundException {\n    exception.expect(NotFoundException.class);\n    exception.expectMessage(containsString(\"algo que indique que a exceção certa ocorreu\"));\n    find(\"função que deveria lançar uma exceção\");\n    // Ponto que nunca deveria ser alcançado quando o teste passar\n}\n","language":"java"},"children":[{"type":"element","tag":"pre","props":{},"children":[{"type":"element","tag":"code","props":{"__ignoreMap":""},"children":[{"type":"element","tag":"span","props":{"class":"line"},"children":[{"type":"element","tag":"span","props":{},"children":[{"type":"text","value":"\n@Test\npublic void example3() throws NotFoundException {\n    exception.expect(NotFoundException.class);\n    exception.expectMessage(containsString(\"algo que indique que a exceção certa ocorreu\"));\n    find(\"função que deveria lançar uma exceção\");\n    // Ponto que nunca deveria ser alcançado quando o teste passar\n}"}]}]}]}]}]},{"type":"element","tag":"ul","props":{},"children":[{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Vantagens:"},{"type":"element","tag":"ul","props":{},"children":[{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Mais de uma expetativa sobre a mesma exceção podem ser testadas após o teste"}]}]}]},{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Desvantagens:"},{"type":"element","tag":"ul","props":{},"children":[{"type":"element","tag":"li","props":{},"children":[{"type":"text","value":"Não é possível realizar outros testes após o "},{"type":"element","tag":"code-inline","props":{},"children":[{"type":"text","value":"find"}]}]}]}]}]},{"type":"element","tag":"h2","props":{"id":"referências"},"children":[{"type":"text","value":"Referências"}]},{"type":"element","tag":"ul","props":{},"children":[{"type":"element","tag":"li","props":{},"children":[{"type":"element","tag":"a","props":{"href":"http://baddotrobot.com/blog/2012/03/27/expecting-exception-with-junit-rule/","rel":["nofollow"]},"children":[{"type":"text","value":"Expecting Exceptions JUnit Rule"}]}]}]}],"toc":{"title":"","searchDepth":2,"depth":2,"links":[{"id":"usando-bloco-trycatch","depth":2,"text":"Usando bloco try/catch"},{"id":"test-expected--exceptionclass","depth":2,"text":"@Test (expected = Exception.class)"},{"id":"expectedexception-rule","depth":2,"text":"ExpectedException Rule"},{"id":"referências","depth":2,"text":"Referências"}]}},"_type":"markdown","_id":"content:til:junit-excecao.md","_source":"content","_file":"til/junit-excecao.md","_extension":"md"}]